# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - libudunits2-dev

r:
  - release

# Add GDAL, GEOS, proj, and units2 dependencies

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# Binary versions of packages to reduce build time.

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings
warnings_are_errors: false
