---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# genestdwp

<!-- badges: start -->
<!-- badges: end -->

The goal of genestdwp is to ...

## Installation

You can install the released version of genestdwp from [Github](https://https://github.com/) with:

``` r
library(devtools)
install_github("PauloEduardoCardoso/genestdwp")
```

## Example

This is a basic example:

```{r example, warning=FALSE}
library(genestdwp)
library(genestdwp)
library(sf)
library(ggplot2)
library(sf)
library(tidyverse)
# Vector of distances
dist = units::set_units(c(10, 20, 30, 40, 50), m)
# Spatial join among visibility map and rings
rings <- genestdwp::viring(x=visib, d = dist)
# Carcasses
pto_carcass
unique(pto_carcass$tamanho)
# Get DWP
dfdwp <- dwp(vr = rings, pt = pto_carcass)
dfdwp
# Plot some data together
ggplot() +
  geom_sf(aes(fill = as.numeric(dist)), colour = 'black',
          size = .8, data = filter(rings, ag == 1)) +
  geom_sf(data = filter(pto_carcass, ag == 1)) +
  theme_void()
```
